name: Build Project
on:
   workflow_dispatch:
    inputs:
      tag_value:
        description: 'Specify tag(x.x.x)'     
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: |
          cd asp.net.solution1
          dotnet restore
    - name: Build
      run: |
          cd asp.net.solution1
          dotnet build --no-restore
          dotnet publish

    - uses: actions/upload-artifact@v3
      with:
        name: publish_artifacts
        path: ./asp.net.solution1/asp.net.solution/bin/Debug/netcoreapp3.1/publish/
        retention-days: 5
