name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
#defaults:
#  run:
#    working-directory: asp.net.solution1
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: create directory DependentLibrary
      run: |
        pwd
        ls
        cd ..
        mkdir DependentLibrary


    - name: Clone DependentLibrary
      uses: actions/checkout@v3
      with:
        repository: e-simo/DependentLibrary
        token: ${{ secrets.ACCESS_TOKEN }}
        path: ../DependentLibrary

    - name: Experiment
      run: |
        pwd
        ls
        cd asp.net.solution1
        pwd
        ls
        cd ..
        cd asp.net.solution1
        pwd
        ls
        cd asp.net.solution
        pwd
        ls
        dotnet restore
        dotnet build --no-restore
       
        

    #- name: Restore dependencies
    #  run: dotnet restore
    #- name: Build
    #  run: dotnet build --no-restore
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
    #- name: Download all workflow run artifacts
    #  uses: actions/download-artifact@v3

    #- name: Experiment
    #  run: |
    #    cd /asp.net.sample/DependentLibrary
    #    pwd
    #    ls
    #    dotnet restore
    #    dotnet build --no-restore

    #- name: Experiment1
    #  run: |
    #    cd ..
    #    cd asp.net.sample/asp.net.solution1/asp.net.solution
    #    pwd
    #    ls
    #    dotnet restore
    #    dotnet build --no-restore