name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

#defaults:
#  run:
#    working-directory: asp.net.solution1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Checkout private tools
      uses: actions/checkout@v3
      #if: github.event_name == 'push' && steps.setup.outputs.has_token == 'true'
      with:
        repository: e-simo/DependentLibrary
        token: ${{ secrets.GH_PAT }}
        path: .
    #- uses: actions/checkout@v1  
    #  with:
    #    repository: e-simo/DependentLibrary
    #    token: ${{ secrets.id_rsa }}
    #- name: Checkout tools repo
    #  uses: actions/checkout@v3
    #  with:
    #    repository: e-simo/DependentLibrary
    #    path: .
    #- name: Setup SSH
    #  uses: MrSquaare/ssh-setup-action@v1
    #  with:
    #      host: github.com
    #      private-key: ${{ secrets.ID_RSA }}
          
    #- name: Clone repository
    #  run: git clone git@github.com:e-simo/DependentLibrary.git

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
