name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
 
    - name: Clone DependentLibrary
      uses: actions/checkout@v3
      with:
        repository: e-simo/DependentLibrary
        token: ${{ secrets.ACCESS_TOKEN }}
        path: ..\..\..\DependentLibrary\

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v3
