name: Dynamic Choice Options

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Select a tag
        options:
          - Loading...

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Get Git Tags
        id: git_tags
        run: |
          git fetch --tags
          tags=$(git tag -l)
          echo "::set-output name=tags::$tags"

      - name: Set Choice Input Options
        if: steps.git_tags.outputs.tags != ''
        id: set_choice_options
        run: |
          tags="${{ steps.git_tags.outputs.tags }}"
          options=$(echo "$tags" | sed 's/\(.*\)/\1/g')
          echo "::set-output name=choice_options::$options"

      - name: Run Workflow
        run: |
          selected_tag="${{ inputs.choice }}"
          echo "Selected tag: $selected_tag"