name: Variables test

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
      boolean:
        type: boolean
        description: True or False
      choice:
        type: choice
        description: Make a choice
        options:
        - foo
        - bar
        - baz
env:
  DAY_OF_WEEK: Monday
  SOURCE_ACTION_DEPLOY_DIR: C:\Users\e.simo\dummydir
  DEPLOY_DIR: C:\Users\e.simo\copydir

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        if: ${{ env.DAY_OF_WEEK == 'Monday' }}
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona
      - name: "Copy stuff"
        run: cp -r $SOURCE_ACTION_DEPLOY_DIR $DEPLOY_DIR
